// Generated by typings
// Source: https://raw.githubusercontent.com/types/npm-gravatar/5b5a86a02df69230cc69abcd34e97ab14a82595e/src/index.d.ts
declare module 'gravatar' {
export function url (email: string, options?: Options, addProtocol?: boolean): string;

export interface Options {
  s?: number | string;
  size?: number | string;
  r?: string;
  rating?: string;
  d?: string;
  default?: string;
  f?: string;
  forcedefault?: string;
}
}
